Repository bcgov/citz-imb-slam-app, pull requests merged in 2022-06, with the labels that each got.

#68 Iod 176
  README.md
  package-lock.json
  package.json
  src/api/common/fetchAPI.js
  src/api/createData.js
  src/api/deleteData.js
  src/api/fetchData.js
  src/api/index.js
  src/components/common/PlainChip.jsx
  src/components/common/SoftwareCell.jsx
  src/components/common/UserMenu.jsx
  src/components/formik/FormikContainer.jsx
  src/components/formik/common/BaseControl.jsx
  src/components/formik/inputs/InputFormikControl.jsx
  src/components/formik/inputs/SelectChipFormikControl.jsx
  src/components/formik/inputs/TextareaFormikControl.jsx
  src/components/formik/inputs/UserListControl.jsx
  src/components/navigation/NavigationLinks.jsx
  src/constants/index.js
  src/hooks/common/Fields.class.js
  src/hooks/common/useDBData.Factory.js
  src/hooks/common/useDBTable.Factory.js
  src/hooks/index.js
  src/hooks/useAPI/fetchAPI.js
  src/hooks/useAPI/useAPI.js
  src/hooks/useAuth/useAuth.js
  src/hooks/useForm/setInitialValues.js
  src/hooks/useLicensees/licenseeFields.js
  src/hooks/useLicensees/useLicensees.js
  src/hooks/useSoftware/softwareFields.js
  src/hooks/useSoftware/useSoftware.js
  src/pages/index.jsx
Labels: breaking change

#83 Iod 226
  .eslintrc.json
  src/components/common/Logo.jsx
  src/components/common/LogoAvatar.jsx
  src/hooks/common/Fields.class.js
  src/hooks/common/useDBData.Factory.js
  src/hooks/index.js
  src/hooks/useAPI/useAPI.js
  src/hooks/useAuth/useAuth.js
  src/hooks/useSoftware/softwareFields.js
  src/pages/_app.jsx
  src/pages/licensees/[id]/index.jsx
  src/pages/licensees/add.jsx
  src/pages/software/[id]/index.jsx
  src/pages/software/add.jsx
  src/pages/software/index.jsx
Labels: bug

#91 IOD-232 Combine License Management Icon and Text into one link
  src/components/navigation/Navigation.jsx
Labels: frontend
